name: CSV Linter and Trailing Whitespaces

on:
  push:
  pull_request:

jobs:
  lint_and_check_trailing_whitespaces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install csvkit

      - name: Validate CSV structure
        run: |
          echo "Checking CSV structure..."
          if ! csvclean --dry-run prompts.csv > /tmp/csv_errors.log 2>&1; then
            echo "::error:: CSV validation failed. Check /tmp/csv_errors.log for details."
            cat /tmp/csv_errors.log
            exit 1
          fi

      - name: Check for BOM and Encoding Issues
        run: |
          echo "Checking for UTF-8 BOM..."
          if [[ $(head -c 3 prompts.csv | xxd -p) == "efbbbf" ]]; then
            echo "::error:: UTF-8 BOM detected. Please remove it."
            exit 1
          fi

      - name: Check CSV format
        run: |
          echo "Checking CSV format..."
          python - <<EOF
          import csv, sys
          with open("prompts.csv", "r", encoding="utf-8") as f:
              reader = csv.reader(f)
              headers = next(reader)
              expected_headers = ["act", "prompt"]
              if headers != expected_headers:
                  print(f"::error:: CSV headers must be {expected_headers}, but got {headers}")
                  sys.exit(1)
              for row_num, row in enumerate(reader, start=2):
                  if len(row) != 2:
                      print(f"::error:: Row {row_num} has {len(row)} columns, expected 2: {row}")
                      sys.exit(1)
                  if not row[0].strip() or not row[1].strip():
                      print(f"::error:: Row {row_num} has empty values")
                      sys.exit(1)
          EOF

      - name: Check Trailing Whitespaces
        run: |
          echo "Checking for trailing whitespaces..."
          if grep -E "[[:space:]]+$" prompts.csv; then
            echo "::error:: Found trailing whitespaces in prompts.csv"
            exit 1
          fi
          echo "No trailing whitespaces found"
