name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write  # Required for deployment authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true  # Caches dependencies properly

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4  # Ensure latest version
        
      - name: Build Jekyll Site
        run: |
          bundle install
          bundle exec jekyll build || { echo "Jekyll build failed!" && exit 1; }

      - name: Debug Build Output (Optional)
        run: ls -lah _site

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: _site  # Jekyll output directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
